# ---------- Builder ----------
FROM node:22.18-alpine3.22 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --force

COPY . .
RUN npm run build

# ---------- Runner ----------
FROM node:22.18-alpine3.22
WORKDIR /app
ENV NODE_ENV=production

# Non-root user (extra security)
RUN addgroup -g 1001 nodejs \
 && adduser -u 1001 -G nodejs -s /bin/sh -D nextjs
USER nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]


